#!/usr/bin/python3 -u

'''
    This script is called by `build` command and updates builds timestamp.
'''

import argparse
import os
import sys

from cosalib.builds import Builds, get_local_builds

parser = argparse.ArgumentParser()
parser.add_argument("--workdir", default='.', help="Path to workdir")
args = parser.parse_args()

builds = Builds(args.workdir)

scanned_builds = []

# first, pick up all the builds from the dir itself
scanned_builds = get_local_builds(os.path.join(args.workdir, "builds"))

# just get the trivial case out of the way
if len(scanned_builds) == 0:
    print("No builds found!")
    sys.exit(0)


# sort by timestamp, newest first
scanned_builds = sorted(scanned_builds,
                        key=lambda x: x.timestamp,
                        reverse=True)

builds.raw()['builds'] = []
for build in reversed(scanned_builds):
    for basearch in build.basearches:
        builds.insert_build(build.id, basearch)

builds.bump_timestamp()
print("Build timestamp was updated")
